apiVersion: v1
  
kind: Pod

metadata:
  name: web1
  labels:
      app: web
spec:
  volumes:
  - name: my-volume
    emptyDir: {}

  containers:
  - name: nginx1
    image: nginx:stable-alpine
    volumeMounts:
    - name: my-volume
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 8080
    imagePullPolicy: Always
  
  - name: linux1
    image: debian
    volumeMounts:
    - name: my-volume
      mountPath: /html
    