apiVersion: v1

kind: Deployment

metadata:
  name: deploy-laravel
  labels:
    app: web
  
  spec:
    replicas: 2
    
    selector:
      matchLabels:
      app: web1

    template:
      metadata:
      labels:
        app: web1
    spec:
      containers:
        - name: testk8s-app
          image: sergiohidalgocaceres/k8s-nodejs:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5500
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"