apiVersion: v1
kind: Service
metadata:
  name: testk8s-service
  labels:
    app: testk8s-app
spec:
  type: LoadBalancer
  selector:
    app: testk8s-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5500